//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.OrderServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.SupplierOrderServiceSoap")]
    public interface SupplierOrderServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddOrder(string productName, int productQty, string username, string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddOrderAsync(string productName, int productQty, string username, string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrdersByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOrdersByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteOrder(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteOrderAsync(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateOrder(int orderID, string productName, int productQty, string username, string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateOrderAsync(int orderID, string productName, int productQty, string username, string categoryName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierOrderServiceSoapChannel : ClientWebApplication.OrderServiceReference.SupplierOrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierOrderServiceSoapClient : System.ServiceModel.ClientBase<ClientWebApplication.OrderServiceReference.SupplierOrderServiceSoap>, ClientWebApplication.OrderServiceReference.SupplierOrderServiceSoap {
        
        public SupplierOrderServiceSoapClient() {
        }
        
        public SupplierOrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierOrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierOrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierOrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddOrder(string productName, int productQty, string username, string categoryId) {
            return base.Channel.AddOrder(productName, productQty, username, categoryId);
        }
        
        public System.Threading.Tasks.Task<string> AddOrderAsync(string productName, int productQty, string username, string categoryId) {
            return base.Channel.AddOrderAsync(productName, productQty, username, categoryId);
        }
        
        public System.Data.DataSet GetOrdersByUsername(string username) {
            return base.Channel.GetOrdersByUsername(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOrdersByUsernameAsync(string username) {
            return base.Channel.GetOrdersByUsernameAsync(username);
        }
        
        public void DeleteOrder(int orderID) {
            base.Channel.DeleteOrder(orderID);
        }
        
        public System.Threading.Tasks.Task DeleteOrderAsync(int orderID) {
            return base.Channel.DeleteOrderAsync(orderID);
        }
        
        public void UpdateOrder(int orderID, string productName, int productQty, string username, string categoryName) {
            base.Channel.UpdateOrder(orderID, productName, productQty, username, categoryName);
        }
        
        public System.Threading.Tasks.Task UpdateOrderAsync(int orderID, string productName, int productQty, string username, string categoryName) {
            return base.Channel.UpdateOrderAsync(orderID, productName, productQty, username, categoryName);
        }
    }
}
