//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login.CategoryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoryServiceReference.CategoryWebServiceSoap")]
    public interface CategoryWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name AutoCategoryIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCategoryId", ReplyAction="*")]
        login.CategoryServiceReference.AutoCategoryIdResponse AutoCategoryId(login.CategoryServiceReference.AutoCategoryIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCategoryId", ReplyAction="*")]
        System.Threading.Tasks.Task<login.CategoryServiceReference.AutoCategoryIdResponse> AutoCategoryIdAsync(login.CategoryServiceReference.AutoCategoryIdRequest request);
        
        // CODEGEN: Generating message contract since element name CategoryId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCategory", ReplyAction="*")]
        login.CategoryServiceReference.insertCategoryResponse insertCategory(login.CategoryServiceReference.insertCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<login.CategoryServiceReference.insertCategoryResponse> insertCategoryAsync(login.CategoryServiceReference.insertCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoCategoryIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoCategoryId", Namespace="http://tempuri.org/", Order=0)]
        public login.CategoryServiceReference.AutoCategoryIdRequestBody Body;
        
        public AutoCategoryIdRequest() {
        }
        
        public AutoCategoryIdRequest(login.CategoryServiceReference.AutoCategoryIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoCategoryIdRequestBody {
        
        public AutoCategoryIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoCategoryIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoCategoryIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public login.CategoryServiceReference.AutoCategoryIdResponseBody Body;
        
        public AutoCategoryIdResponse() {
        }
        
        public AutoCategoryIdResponse(login.CategoryServiceReference.AutoCategoryIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoCategoryIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoCategoryIdResult;
        
        public AutoCategoryIdResponseBody() {
        }
        
        public AutoCategoryIdResponseBody(string AutoCategoryIdResult) {
            this.AutoCategoryIdResult = AutoCategoryIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCategory", Namespace="http://tempuri.org/", Order=0)]
        public login.CategoryServiceReference.insertCategoryRequestBody Body;
        
        public insertCategoryRequest() {
        }
        
        public insertCategoryRequest(login.CategoryServiceReference.insertCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CategoryId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CategoryName;
        
        public insertCategoryRequestBody() {
        }
        
        public insertCategoryRequestBody(string CategoryId, string CategoryName) {
            this.CategoryId = CategoryId;
            this.CategoryName = CategoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public login.CategoryServiceReference.insertCategoryResponseBody Body;
        
        public insertCategoryResponse() {
        }
        
        public insertCategoryResponse(login.CategoryServiceReference.insertCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertCategoryResult;
        
        public insertCategoryResponseBody() {
        }
        
        public insertCategoryResponseBody(string insertCategoryResult) {
            this.insertCategoryResult = insertCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoryWebServiceSoapChannel : login.CategoryServiceReference.CategoryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryWebServiceSoapClient : System.ServiceModel.ClientBase<login.CategoryServiceReference.CategoryWebServiceSoap>, login.CategoryServiceReference.CategoryWebServiceSoap {
        
        public CategoryWebServiceSoapClient() {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        login.CategoryServiceReference.AutoCategoryIdResponse login.CategoryServiceReference.CategoryWebServiceSoap.AutoCategoryId(login.CategoryServiceReference.AutoCategoryIdRequest request) {
            return base.Channel.AutoCategoryId(request);
        }
        
        public string AutoCategoryId() {
            login.CategoryServiceReference.AutoCategoryIdRequest inValue = new login.CategoryServiceReference.AutoCategoryIdRequest();
            inValue.Body = new login.CategoryServiceReference.AutoCategoryIdRequestBody();
            login.CategoryServiceReference.AutoCategoryIdResponse retVal = ((login.CategoryServiceReference.CategoryWebServiceSoap)(this)).AutoCategoryId(inValue);
            return retVal.Body.AutoCategoryIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<login.CategoryServiceReference.AutoCategoryIdResponse> login.CategoryServiceReference.CategoryWebServiceSoap.AutoCategoryIdAsync(login.CategoryServiceReference.AutoCategoryIdRequest request) {
            return base.Channel.AutoCategoryIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<login.CategoryServiceReference.AutoCategoryIdResponse> AutoCategoryIdAsync() {
            login.CategoryServiceReference.AutoCategoryIdRequest inValue = new login.CategoryServiceReference.AutoCategoryIdRequest();
            inValue.Body = new login.CategoryServiceReference.AutoCategoryIdRequestBody();
            return ((login.CategoryServiceReference.CategoryWebServiceSoap)(this)).AutoCategoryIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        login.CategoryServiceReference.insertCategoryResponse login.CategoryServiceReference.CategoryWebServiceSoap.insertCategory(login.CategoryServiceReference.insertCategoryRequest request) {
            return base.Channel.insertCategory(request);
        }
        
        public string insertCategory(string CategoryId, string CategoryName) {
            login.CategoryServiceReference.insertCategoryRequest inValue = new login.CategoryServiceReference.insertCategoryRequest();
            inValue.Body = new login.CategoryServiceReference.insertCategoryRequestBody();
            inValue.Body.CategoryId = CategoryId;
            inValue.Body.CategoryName = CategoryName;
            login.CategoryServiceReference.insertCategoryResponse retVal = ((login.CategoryServiceReference.CategoryWebServiceSoap)(this)).insertCategory(inValue);
            return retVal.Body.insertCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<login.CategoryServiceReference.insertCategoryResponse> login.CategoryServiceReference.CategoryWebServiceSoap.insertCategoryAsync(login.CategoryServiceReference.insertCategoryRequest request) {
            return base.Channel.insertCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<login.CategoryServiceReference.insertCategoryResponse> insertCategoryAsync(string CategoryId, string CategoryName) {
            login.CategoryServiceReference.insertCategoryRequest inValue = new login.CategoryServiceReference.insertCategoryRequest();
            inValue.Body = new login.CategoryServiceReference.insertCategoryRequestBody();
            inValue.Body.CategoryId = CategoryId;
            inValue.Body.CategoryName = CategoryName;
            return ((login.CategoryServiceReference.CategoryWebServiceSoap)(this)).insertCategoryAsync(inValue);
        }
    }
}
