//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.ClientWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientWebService.ClientWebServiceSoap")]
    public interface ClientWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetClientDetails(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetClientDetailsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderedItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderedItems(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderedItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetOrderedItemsAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientWebServiceSoapChannel : ClientWebApplication.ClientWebService.ClientWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientWebServiceSoapClient : System.ServiceModel.ClientBase<ClientWebApplication.ClientWebService.ClientWebServiceSoap>, ClientWebApplication.ClientWebService.ClientWebServiceSoap {
        
        public ClientWebServiceSoapClient() {
        }
        
        public ClientWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetClientDetails(string username) {
            return base.Channel.GetClientDetails(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetClientDetailsAsync(string username) {
            return base.Channel.GetClientDetailsAsync(username);
        }
        
        public System.Data.DataTable GetOrderedItems(string username) {
            return base.Channel.GetOrderedItems(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetOrderedItemsAsync(string username) {
            return base.Channel.GetOrderedItemsAsync(username);
        }
    }
}
