//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.LoginRegisterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginRegisterServiceReference.ClientLoginRegisterServiceSoap")]
    public interface ClientLoginRegisterServiceSoap {
        
        // CODEGEN: Generating message contract since element name clientName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterClient", ReplyAction="*")]
        ClientWebApplication.LoginRegisterServiceReference.RegisterClientResponse RegisterClient(ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterClient", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.RegisterClientResponse> RegisterClientAsync(ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientLogin", ReplyAction="*")]
        ClientWebApplication.LoginRegisterServiceReference.ClientLoginResponse ClientLogin(ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.ClientLoginResponse> ClientLoginAsync(ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminLogin", ReplyAction="*")]
        ClientWebApplication.LoginRegisterServiceReference.AdminLoginResponse AdminLogin(ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.AdminLoginResponse> AdminLoginAsync(ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupplierLogin", ReplyAction="*")]
        ClientWebApplication.LoginRegisterServiceReference.SupplierLoginResponse SupplierLogin(ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupplierLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.SupplierLoginResponse> SupplierLoginAsync(ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterClient", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequestBody Body;
        
        public RegisterClientRequest() {
        }
        
        public RegisterClientRequest(ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string username;
        
        public RegisterClientRequestBody() {
        }
        
        public RegisterClientRequestBody(string clientName, int age, string address, string password, string username) {
            this.clientName = clientName;
            this.age = age;
            this.address = address;
            this.password = password;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.LoginRegisterServiceReference.RegisterClientResponseBody Body;
        
        public RegisterClientResponse() {
        }
        
        public RegisterClientResponse(ClientWebApplication.LoginRegisterServiceReference.RegisterClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterClientResult;
        
        public RegisterClientResponseBody() {
        }
        
        public RegisterClientResponseBody(string RegisterClientResult) {
            this.RegisterClientResult = RegisterClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientLogin", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequestBody Body;
        
        public ClientLoginRequest() {
        }
        
        public ClientLoginRequest(ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ClientLoginRequestBody() {
        }
        
        public ClientLoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.LoginRegisterServiceReference.ClientLoginResponseBody Body;
        
        public ClientLoginResponse() {
        }
        
        public ClientLoginResponse(ClientWebApplication.LoginRegisterServiceReference.ClientLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ClientLoginResult;
        
        public ClientLoginResponseBody() {
        }
        
        public ClientLoginResponseBody(string ClientLoginResult) {
            this.ClientLoginResult = ClientLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdminLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdminLogin", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequestBody Body;
        
        public AdminLoginRequest() {
        }
        
        public AdminLoginRequest(ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdminLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AdminLoginRequestBody() {
        }
        
        public AdminLoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdminLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdminLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.LoginRegisterServiceReference.AdminLoginResponseBody Body;
        
        public AdminLoginResponse() {
        }
        
        public AdminLoginResponse(ClientWebApplication.LoginRegisterServiceReference.AdminLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdminLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdminLoginResult;
        
        public AdminLoginResponseBody() {
        }
        
        public AdminLoginResponseBody(bool AdminLoginResult) {
            this.AdminLoginResult = AdminLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SupplierLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SupplierLogin", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequestBody Body;
        
        public SupplierLoginRequest() {
        }
        
        public SupplierLoginRequest(ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SupplierLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SupplierLoginRequestBody() {
        }
        
        public SupplierLoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SupplierLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SupplierLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.LoginRegisterServiceReference.SupplierLoginResponseBody Body;
        
        public SupplierLoginResponse() {
        }
        
        public SupplierLoginResponse(ClientWebApplication.LoginRegisterServiceReference.SupplierLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SupplierLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SupplierLoginResult;
        
        public SupplierLoginResponseBody() {
        }
        
        public SupplierLoginResponseBody(bool SupplierLoginResult) {
            this.SupplierLoginResult = SupplierLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientLoginRegisterServiceSoapChannel : ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientLoginRegisterServiceSoapClient : System.ServiceModel.ClientBase<ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap>, ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap {
        
        public ClientLoginRegisterServiceSoapClient() {
        }
        
        public ClientLoginRegisterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientLoginRegisterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientLoginRegisterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientLoginRegisterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.LoginRegisterServiceReference.RegisterClientResponse ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap.RegisterClient(ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequest request) {
            return base.Channel.RegisterClient(request);
        }
        
        public string RegisterClient(string clientName, int age, string address, string password, string username) {
            ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequest inValue = new ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequest();
            inValue.Body = new ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequestBody();
            inValue.Body.clientName = clientName;
            inValue.Body.age = age;
            inValue.Body.address = address;
            inValue.Body.password = password;
            inValue.Body.username = username;
            ClientWebApplication.LoginRegisterServiceReference.RegisterClientResponse retVal = ((ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap)(this)).RegisterClient(inValue);
            return retVal.Body.RegisterClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.RegisterClientResponse> ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap.RegisterClientAsync(ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequest request) {
            return base.Channel.RegisterClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.RegisterClientResponse> RegisterClientAsync(string clientName, int age, string address, string password, string username) {
            ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequest inValue = new ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequest();
            inValue.Body = new ClientWebApplication.LoginRegisterServiceReference.RegisterClientRequestBody();
            inValue.Body.clientName = clientName;
            inValue.Body.age = age;
            inValue.Body.address = address;
            inValue.Body.password = password;
            inValue.Body.username = username;
            return ((ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap)(this)).RegisterClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.LoginRegisterServiceReference.ClientLoginResponse ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap.ClientLogin(ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequest request) {
            return base.Channel.ClientLogin(request);
        }
        
        public string ClientLogin(string username, string password) {
            ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequest inValue = new ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequest();
            inValue.Body = new ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ClientWebApplication.LoginRegisterServiceReference.ClientLoginResponse retVal = ((ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap)(this)).ClientLogin(inValue);
            return retVal.Body.ClientLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.ClientLoginResponse> ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap.ClientLoginAsync(ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequest request) {
            return base.Channel.ClientLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.ClientLoginResponse> ClientLoginAsync(string username, string password) {
            ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequest inValue = new ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequest();
            inValue.Body = new ClientWebApplication.LoginRegisterServiceReference.ClientLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap)(this)).ClientLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.LoginRegisterServiceReference.AdminLoginResponse ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap.AdminLogin(ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequest request) {
            return base.Channel.AdminLogin(request);
        }
        
        public bool AdminLogin(string username, string password) {
            ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequest inValue = new ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequest();
            inValue.Body = new ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ClientWebApplication.LoginRegisterServiceReference.AdminLoginResponse retVal = ((ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap)(this)).AdminLogin(inValue);
            return retVal.Body.AdminLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.AdminLoginResponse> ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap.AdminLoginAsync(ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequest request) {
            return base.Channel.AdminLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.AdminLoginResponse> AdminLoginAsync(string username, string password) {
            ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequest inValue = new ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequest();
            inValue.Body = new ClientWebApplication.LoginRegisterServiceReference.AdminLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap)(this)).AdminLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.LoginRegisterServiceReference.SupplierLoginResponse ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap.SupplierLogin(ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequest request) {
            return base.Channel.SupplierLogin(request);
        }
        
        public bool SupplierLogin(string username, string password) {
            ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequest inValue = new ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequest();
            inValue.Body = new ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ClientWebApplication.LoginRegisterServiceReference.SupplierLoginResponse retVal = ((ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap)(this)).SupplierLogin(inValue);
            return retVal.Body.SupplierLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.SupplierLoginResponse> ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap.SupplierLoginAsync(ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequest request) {
            return base.Channel.SupplierLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.LoginRegisterServiceReference.SupplierLoginResponse> SupplierLoginAsync(string username, string password) {
            ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequest inValue = new ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequest();
            inValue.Body = new ClientWebApplication.LoginRegisterServiceReference.SupplierLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ClientWebApplication.LoginRegisterServiceReference.ClientLoginRegisterServiceSoap)(this)).SupplierLoginAsync(inValue);
        }
    }
}
